version: "3.9"

services:
  backend:
    build: .\server 
    ports:
    - "8000:8000"
    volumes:
      - ./server:/app
  frontend:
    build: ./frontend
    ports:
    - "3000:3000"
    volumes:
    - ./frontend:/user/src/app
    depends_on:
    - backend
