version: "3.9"

services:
  server:
    build: .\server 
    ports:
    - "8000:8000"
    volumes:
      - .\server:\app
  web:
    build: ./frontend
    ports:
    - "3000:3000"
    volumes:
    - ./frontend:/user/src/app
    depends_on:
    - server
